Traceback (most recent call last):
  File "C:\anaconda\envs\jbook\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\anaconda\envs\jbook\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df.to_csv('./data/ebooks_data.csv')
df.to_csv('./app/data/ebooks_data.csv')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_12796\1254726040.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [0mdf[0m[1;33m.[0m[0mto_csv[0m[1;33m([0m[1;34m'./data/ebooks_data.csv'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mdf[0m[1;33m.[0m[0mto_csv[0m[1;33m([0m[1;34m'./app/data/ebooks_data.csv'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32mC:\anaconda\envs\jbook\lib\site-packages\pandas\core\generic.py[0m in [0;36mto_csv[1;34m(self, path_or_buf, sep, na_rep, float_format, columns, header, index, index_label, mode, encoding, compression, quoting, quotechar, line_terminator, chunksize, date_format, doublequote, escapechar, decimal, errors, storage_options)[0m
[0;32m   3480[0m             [0mdoublequote[0m[1;33m=[0m[0mdoublequote[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m   3481[0m             [0mescapechar[0m[1;33m=[0m[0mescapechar[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 3482[1;33m             [0mstorage_options[0m[1;33m=[0m[0mstorage_options[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   3483[0m         )
[0;32m   3484[0m [1;33m[0m[0m

[1;32mC:\anaconda\envs\jbook\lib\site-packages\pandas\io\formats\format.py[0m in [0;36mto_csv[1;34m(self, path_or_buf, encoding, sep, columns, index_label, mode, compression, quoting, quotechar, line_terminator, chunksize, date_format, doublequote, escapechar, errors, storage_options)[0m
[0;32m   1103[0m             [0mformatter[0m[1;33m=[0m[0mself[0m[1;33m.[0m[0mfmt[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1104[0m         )
[1;32m-> 1105[1;33m         [0mcsv_formatter[0m[1;33m.[0m[0msave[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1106[0m [1;33m[0m[0m
[0;32m   1107[0m         [1;32mif[0m [0mcreated_buffer[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\anaconda\envs\jbook\lib\site-packages\pandas\io\formats\csvs.py[0m in [0;36msave[1;34m(self)[0m
[0;32m    241[0m             [0merrors[0m[1;33m=[0m[0mself[0m[1;33m.[0m[0merrors[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    242[0m             [0mcompression[0m[1;33m=[0m[0mself[0m[1;33m.[0m[0mcompression[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 243[1;33m             [0mstorage_options[0m[1;33m=[0m[0mself[0m[1;33m.[0m[0mstorage_options[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    244[0m         ) as handles:
[0;32m    245[0m [1;33m[0m[0m

[1;32mC:\anaconda\envs\jbook\lib\site-packages\pandas\io\common.py[0m in [0;36mget_handle[1;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[0;32m    705[0m                 [0mencoding[0m[1;33m=[0m[0mioargs[0m[1;33m.[0m[0mencoding[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    706[0m                 [0merrors[0m[1;33m=[0m[0merrors[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 707[1;33m                 [0mnewline[0m[1;33m=[0m[1;34m""[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    708[0m             )
[0;32m    709[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: './app/data/ebooks_data.csv'
FileNotFoundError: [Errno 2] No such file or directory: './app/data/ebooks_data.csv'

